// @ts-check

const sidebars = {
  /* Generate the sidebar from the hierarchy of filesystem. */
  documentSidebar: [{type: 'autogenerated', dirName: '.'}],
};

// noinspection JSUnusedGlobalSymbols
export default sidebars;
