// @ts-check

const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  documentSidebar: [{type: 'autogenerated', dirName: '.'}],
};

// noinspection JSUnusedGlobalSymbols
export default sidebars;
